In [6]:
pip install plotly

In [84]:
import pandas as pd
import numpy as np
import plotly.offline as py
import plotly.graph_objs as go
import plotly.figure_factory as ff
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss


In [44]:
df = pd.read_csv("/content/mental_health_dataset.csv")
df

age      gender  ... productivity_score mental_health_risk
0      56        Male  ...               59.7               High
1      46      Female  ...               54.9               High
2      32      Female  ...               61.3             Medium
3      60  Non-binary  ...               97.0                Low
4      25      Female  ...               69.0               High
...   ...         ...  ...                ...                ...
9995   34      Female  ...               90.0             Medium
9996   47        Male  ...               90.8             Medium
9997   56      Female  ...               99.2             Medium
9998   24        Male  ...               56.7               High
9999   44        Male  ...              100.0             Medium

[10000 rows x 14 columns]

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   age                     10000 non-null  int64  
 1   gender                  10000 non-null  object 
 2   employment_status       10000 non-null  object 
 3   work_environment        10000 non-null  object 
 4   mental_health_history   10000 non-null  object 
 5   seeks_treatment         10000 non-null  object 
 6   stress_level            10000 non-null  int64  
 7   sleep_hours             10000 non-null  float64
 8   physical_activity_days  10000 non-null  int64  
 9   depression_score        10000 non-null  int64  
 10  anxiety_score           10000 non-null  int64  
 11  social_support_score    10000 non-null  int64  
 12  productivity_score      10000 non-null  float64
 13  mental_health_risk      10000 non-null  object 
dtypes: float64(2), int64(6), object(6)
memo

In [46]:
df.describe

<bound method NDFrame.describe of       age      gender  ... productivity_score mental_health_risk
0      56        Male  ...               59.7               High
1      46      Female  ...               54.9               High
2      32      Female  ...               61.3             Medium
3      60  Non-binary  ...               97.0                Low
4      25      Female  ...               69.0               High
...   ...         ...  ...                ...                ...
9995   34      Female  ...               90.0             Medium
9996   47        Male  ...               90.8             Medium
9997   56      Female  ...               99.2             Medium
9998   24        Male  ...               56.7               High
9999   44        Male  ...              100.0             Medium

[10000 rows x 14 columns]>

In [47]:
df.dtypes

age                         int64
gender                     object
employment_status          object
work_environment           object
mental_health_history      object
seeks_treatment            object
stress_level                int64
sleep_hours               float64
physical_activity_days      int64
depression_score            int64
anxiety_score               int64
social_support_score        int64
productivity_score        float64
mental_health_risk         object
dtype: object

In [48]:
df.isnull().sum()

age                       0
gender                    0
employment_status         0
work_environment          0
mental_health_history     0
seeks_treatment           0
stress_level              0
sleep_hours               0
physical_activity_days    0
depression_score          0
anxiety_score             0
social_support_score      0
productivity_score        0
mental_health_risk        0
dtype: int64

In [49]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
df['mental_health_risk_Encoder'] = le.fit_transform(df['mental_health_risk'])
df['gender_Encoder']= le.fit_transform(df['gender'])
df['mental_health_history_Encoder'] = le.fit_transform(df['mental_health_history'])
df['seeks_treatment_Encoder'] = le.fit_transform(df['seeks_treatment'])
df.head()

age      gender  ... mental_health_history_Encoder seeks_treatment_Encoder
0   56        Male  ...                             1                       1
1   46      Female  ...                             0                       1
2   32      Female  ...                             1                       0
3   60  Non-binary  ...                             0                       0
4   25      Female  ...                             1                       1

[5 rows x 18 columns]

In [50]:
df.drop(columns=['mental_health_risk','gender','work_environment','mental_health_history','seeks_treatment','employment_status'],inplace=True)
df.head()

age  stress_level  ...  mental_health_history_Encoder  seeks_treatment_Encoder
0   56             6  ...                              1                        1
1   46            10  ...                              0                        1
2   32             7  ...                              1                        0
3   60             4  ...                              0                        0
4   25             3  ...                              1                        1

[5 rows x 12 columns]

In [51]:
X=df.drop(columns =['mental_health_risk_Encoder'])
X.head()

age  stress_level  ...  mental_health_history_Encoder  seeks_treatment_Encoder
0   56             6  ...                              1                        1
1   46            10  ...                              0                        1
2   32             7  ...                              1                        0
3   60             4  ...                              0                        0
4   25             3  ...                              1                        1

[5 rows x 11 columns]

In [52]:
y=df['mental_health_risk_Encoder']
y

0       0
1       0
2       2
3       1
4       0
       ..
9995    2
9996    2
9997    2
9998    0
9999    2
Name: mental_health_risk_Encoder, Length: 10000, dtype: int64

In [53]:
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2)


In [54]:
X_train.shape

(8000, 11)

In [55]:
X_test.shape

(2000, 11)

In [58]:
model = LogisticRegression()
model.fit(X_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression



LogisticRegression()

In [63]:
y_pred = model.predict(X_test)
y_pred

array([1, 1, 2, ..., 2, 2, 0])

In [64]:
y_pred = model.predict(X_train)
y_pred

array([2, 2, 2, ..., 0, 1, 0])

In [74]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
y_pred = model.predict(X_test)
# Assuming y_true and y_pred (predicted classes from probabilities)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 0.954
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.94      0.93       485
           1       0.98      0.95      0.96       342
           2       0.96      0.96      0.96      1173

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000

Confusion Matrix:
 [[ 456    0   29]
 [   0  324   18]
 [  39    6 1128]]


In [76]:
y_pred_probs = model.predict_proba(X_test)
log_loss_value = log_loss(y_test, y_pred_probs)
print("Logg Loss value:", log_loss_value)

Logg Loss value: 0.10127401835899405


## ***Average Anxiety by Gender***

In [82]:
fig = px.bar(df,x='gender_Encoder', y='anxiety_score',
             title='Average Anxiety by Gender',
             color='gender_Encoder',
             barmode='group',
             height=400)
fig.show()


In [83]:
corr_matrix = df[['stress_level', 'sleep_hours', 'physical_activity_days',
                  'depression_score', 'anxiety_score',
                  'social_support_score', 'productivity_score']].corr()
fig = ff.create_annotated_heatmap(
    z=corr_matrix.values,
    x=list(corr_matrix.columns),
    y=list(corr_matrix.index),
    annotation_text=corr_matrix.round(2).values,
    colorscale='Viridis'
)
fig.update_layout(title='Correlation Between Mental Health Indicators')
fig.show()
